name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifacts-name:
        description: The name of the deployable files
        required: false
        default: dist
        type: string
    secrets:
      some-secret:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifacts-name}}
      - name: Get Secrets
        run: ${{secrets.some-secret}}

      - name: List Files
        run: ls
      - name: Output-Infotmation
        run: echo "deploying output Info"
